version: "3"

services:
  laravel:
    # o build cria a imagem de acordo com o dockerfile
    # daí não presisa baixar uma imagem pronta do projeto
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: rocheleedenis/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: rocheleedenis/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge