version: "3"

services:
  app:
    build:
      context: app
    container_name: app
    networks:
      - desafio
    volumes:
    # remover depois
      - ./app:/app
    tty: true
    depends_on:
      - mysql

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - desafio
    ports:
      - "8080:80"
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    # habilita a forma de interação para caso a gente precise entrar no container
    # para rodar algum comando manualmente
    tty: true
    environment:
      - MYSQL_DATABASE=desafio
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio

networks:
  desafio:
    driver: bridge
