version: "3"

services:
  app:
    build:
      context: app
    container_name: app
    networks:
      - desafio
    entrypoint: wait-for mysql:3306 -t 20 -- node index.js
    depends_on:
      - mysql

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - desafio
    ports:
      - "8080:80"
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafio
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio

networks:
  desafio:
    driver: bridge
