# A idéia principal é que quando um usuário acesse o nginx, o mesmo fará uma chamada em nossa aplicação node.js. Essa aplicação por sua vez adicionará um registro em nosso banco de dados mysql, cadastrando um nome na tabela people.
# O retorno da aplicação node.js para o nginx deverá ser:
# <h1>Full Cycle Rocks!</h1>
# - Lista de nomes cadastrada no banco de dados.
# Gere o docker-compose de uma forma que basta apenas rodarmos: docker-compose up -d que tudo deverá estar funcionando e disponível na porta: 8080.
# Suba tudo em um repositório e faça a entrega.

version: "3"

services:
  app:
    build:
      context: app
    container_name: app
    networks:
      - desafio
    volumes:
    # remover depois
      - ./app:/usr/src/app
    tty: true
    depends_on:
      - mysql

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - desafio
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  desafio:
    driver: bridge
